package com.example.bookstorage.book;

public enum BookGenre
{
    COMPUTER_SCIENCE, PROGRAMMING, SOFTWARE_ENGINEERING, HISTORICAL_FICTION,
    ROMANCE, PSYCHOLOGICAL_FICTION, MODERNIST_LITERATURE, MAGICAL_REALISM
}